name: Ubuntu latest C/C++ (no features)

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ubuntu-latest
        configure_args:
          - >-
            --enable-html-matrix=no
            --enable-parallel=no
            --enable-pytest=no
            --enable-shared=yes
            --enable-silent-rules
            --enable-static=yes
            --enable-usrp=no
            --enable-winradio=no
            --with-cxx-binding=no
            --with-indi=no
            --with-libusb=no
            --with-lua-binding=no
            --with-perl-binding=no
            --with-python-binding=no
            --with-readline=no
            --with-tcl-binding=no
            --with-xml-support=no

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies on Ubuntu latest
      run: |
        sudo apt update
        sudo apt install libusb-1.0-0-dev
        sudo apt install libgd-dev
        sudo apt install libgpiod-dev
        sudo apt install libindi-dev libnova-dev
        sudo apt install grep
        sudo apt install python3-dev python3-pytest
        sudo apt install lua5.4 liblua5.4-dev libperl-dev tcl-dev
    - name: bootstrap
      run: |
        pwd
        ./bootstrap
    - name: README Debug
      run: grep README Makefile.am
    - name: configure
      run: ./configure ${{ matrix.configure_args }}
    - name: make
      run: make -j 4 V=0 --no-print-directory
    - name: make distcheck
      run: make distcheck V=0 --no-print-directory AM_DISTCHECK_CONFIGURE_FLAGS="${{ matrix.configure_args }}"
    - name: 'Tar files'
      run: tar -cvf ubuntu_latest_no_features.tar .
    - name: 'Upload Build Artifacts'
      uses: actions/upload-artifact@v4.6.2
      with:
        name: 'Ubuntu_latest_no_features'
        path: Hamlib
